services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ghady
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped
  demo:
    container_name: demo
    image: ghady22/demo
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/customer
    ports:
      - "8080:8080"
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped
  demo-react:
    container_name: demo-react
    image: ghady22/demo-react
    build:
      context: Frontend/react
      args:
        api_base_url: http://localhost:8080
    ports:
      - "3000:5173"
    depends_on:
      - demo
    restart: unless-stopped


networks:
  db:
    driver: bridge

volumes:
  db:
